version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb 
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /var/tmp
      - sockets:/app/tmp/sockets
    tty: true
    depends_on:
      - db
    extends:
      file: ./docker/mysql/password.yml
      service: password
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    volumes:
      ## 下で用意したdb_dataとマウント共有。 /var/lib/mysqlがデータディレクトリ
      - db_data:/var/lib/mysql
    extends:  ##拡張
      file: ./docker/mysql/password.yml
      service: password
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
      #他のサービスのボリュームをマウント 実際にnginxのコンテナの中にappディレクトリが存在している。
    volumes: 
      - sockets:/app/tmp/sockets
    depends_on: 
      - app

volumes:
  db_data:
  sockets:

    ##docker-compose run --rm web rails new . --force --database=mysql  --skip-test --api