version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          region: ${AWS_DEFAULT_REGION}
          aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          create-repo: true
          path: ../docker/nginx/.
          repo: "nginx"
          tag: "latest"
          filters:
            branches:
              only: master