version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          path: ./docker/nginx
          repo: "nginx"
          tag: "latest"
          workspace-root: ./docker/nginx
          filters:
            branches:
              only: master