name: Deploy

on:
  # master ブランチにプッシュされた場合に動作する
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # GitHub リポジトリからコードを引っ張ってくる
      - name: Checkout
        uses: actions/checkout@v2
      # 前回のコンテナキャッシュがあれば使用する。なければキャッシュを作る
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Ruby をインストールする
      - name: Set up Ruby 2.6
        ruby/setup-ruby
        with:
          ruby-version: 2.6
      # バンドラーをインストールし、初期化する
      - name: Bundle install
        run: |
          rm -rf $GEM_HOME/bundler/ $GEM_HOME/cache/bundler/
          rm -rf .bundle/
          rm -rf vendor/cache/
          rm -rf Gemfile.lock
          bundle install
      # ヘロクにデプロイする
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "fishing-map-api"
          heroku_email: "acbmstk0402@gmail.com"