name: Deploy

on:
  # master ブランチにプッシュされた場合に動作する
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # GitHub リポジトリからコードを引っ張ってくる
      - name: Checkout
        uses: actions/checkout@v2
      # 前回のコンテナキャッシュがあれば使用する。なければキャッシュを作る
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Ruby をインストールする
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          version: 2.6.3
      - name: Build
        run: |
          gem install bundler:1.17.2
      # - name: lint
      #   run: bundle exec rubocop
      # - name: rspec
      #   run: bundle exec rspec
      # ヘロクにデプロイする
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "fishing-map-api"
          heroku_email: "acbmstk0402@gmail.com"